<?php
require_once __DIR__.'/../config/conexion.php';
require_once __DIR__.'/../config/funciones.php';
require_once __DIR__.'/../config/auth.php';
require_once __DIR__.'/../config/esquema.php';
protegerPanelAdmin(); asegurarEsquemaBoutique($conexion);
$admin=adminActual(); $empresa=obtenerEmpresa($conexion);
$totalProductos=(int)$conexion->query("SELECT COUNT(*) FROM productos WHERE estado_producto=1")->fetchColumn();
$totalClientes=(int)$conexion->query("SELECT COUNT(*) FROM clientes WHERE estado_cliente=1")->fetchColumn();
$totalPedidos=(int)$conexion->query("SELECT COUNT(*) FROM pedidos")->fetchColumn();
$pendientes=(int)$conexion->query("SELECT COUNT(*) FROM pedidos WHERE estado_pedido='pendiente'")->fetchColumn();
$pedidos=$conexion->query("SELECT * FROM pedidos ORDER BY id_pedido DESC LIMIT 8")->fetchAll();
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/webp" href="../assets/img/favicon-boutique.jpg"><title>Panel | <?=htmlspecialchars($empresa['nombre_empresa']??'Boutique')?></title><link rel="stylesheet" href="../assets/css/estilos.css?v=16.0"></head>
<body class="admin-body"><div class="admin-layout clean-admin"><aside class="admin-sidebar admin-sidebar-full"><div class="admin-sidebar-brand"><span class="admin-logo-mini">BG</span><div><strong><?=htmlspecialchars($empresa['nombre_empresa']??'Boutique')?></strong><small>Administración</small></div></div>
<nav class="admin-nav" aria-label="Menú administrador">
            <a class="activo" href="administrador.php"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/></svg> Dashboard</a>
            <a href="productos.php"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M16.5 9.4 7.55 4.24"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/></svg> Productos</a>
            <a href="clientes.php"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg> Clientes</a>
            <a href="pedidos.php"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"/><path d="M3 6h18"/><path d="M16 10a4 4 0 0 1-8 0"/></svg> Pedidos</a>
            <a href="categorias.php"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/></svg> Categorías</a>
            <a href="marcas.php"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z"/><circle cx="7.5" cy="7.5" r=".5" fill="currentColor"/></svg> Marcas</a>
            <a href="../index.php" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg> Ver tienda</a>
        </nav>
<div class="admin-sidebar-box">
    <span>Resumen</span>
    <strong><?= $totalPedidos ?></strong>
    <small>pedidos registrados</small>
</div>
<div class="admin-sidebar-shortcuts"><a href="clientes.php#form-cliente">+ Cliente</a><a href="pedidos.php#form-pedido">+ Pedido</a><a href="productos.php#form-producto">+ Producto</a></div>
<div class="admin-sidebar-footer"><span><?=htmlspecialchars($admin['nombre']??'Admin')?></span><a href="logout.php"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg> Salir</a></div></aside>
<main class="admin-main"><header class="admin-topbar"><div><span class="admin-kicker">Resumen</span><h1>Panel de control</h1><p>Accesos rápidos para clientes, pedidos y catálogo.</p></div><div class="admin-quick-actions"><a class="admin-btn primary" href="clientes.php#form-cliente">+ Cliente</a><a class="admin-btn" href="pedidos.php#form-pedido">+ Pedido</a></div></header>
<section class="admin-stats-grid">
    <article><span class="admin-stat-icono"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M16.5 9.4 7.55 4.24"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/></svg></span><span>Productos</span><strong><?=$totalProductos?></strong></article>
    <article><span class="admin-stat-icono"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></span><span>Clientes</span><strong><?=$totalClientes?></strong></article>
    <article><span class="admin-stat-icono"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"/><path d="M3 6h18"/><path d="M16 10a4 4 0 0 1-8 0"/></svg></span><span>Pedidos</span><strong><?=$totalPedidos?></strong></article>
    <article><span class="admin-stat-icono"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></span><span>Pendientes</span><strong><?=$pendientes?></strong></article>
</section>
<section class="admin-panel-card"><div class="admin-panel-header"><div><h2>Pedidos recientes</h2><p>Últimos pedidos registrados.</p></div><a class="admin-btn small ghost" href="pedidos.php">Ver todos</a></div><div class="admin-table-wrap normal-table"><table class="admin-table"><thead><tr><th>Código</th><th>Cliente</th><th>Retiro</th><th>Total</th><th>Estado</th><th>Fecha</th></tr></thead><tbody><?php foreach($pedidos as $p):?><tr><td><strong><?=htmlspecialchars($p['codigo_pedido'])?></strong></td><td><?=htmlspecialchars($p['nombre_cliente'])?></td><td><?=htmlspecialchars($p['tipo_retiro']==='delivery'?'Delivery':'Local')?></td><td><?=formatearPrecio($p['total_pedido'])?></td><td><span class="admin-badge <?=$p['estado_pedido']==='pendiente'?'muted':'ok'?>"><?=htmlspecialchars(ucfirst($p['estado_pedido']))?></span></td><td><?=date('d/m/Y H:i',strtotime($p['fecha_pedido']))?></td></tr><?php endforeach;?><?php if(!$pedidos):?><tr><td colspan="6" class="admin-empty">Aún no hay pedidos.</td></tr><?php endif;?></tbody></table></div></section>
</main></div></body></html>